version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: ticket-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ticket-booking

  redis:
    image: redis:7-alpine
    container_name: ticket-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
